# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('descr', models.TextField(max_length=220)),
                ('image', models.ImageField(upload_to='books')),
                ('is_active', models.BooleanField(default=True)),
                ('bidders', models.ManyToManyField(blank=True, db_table='bidders', related_name='offer_users', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
    ]
