# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.TextField(max_length=50),
        ),
    ]
