# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Males'), ('F', 'Female')], max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(upload_to='users')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
